// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eolarity-redesign/Current.tsx": () => import("../components/mockups/eolarity-redesign/Current.tsx"),
  "./components/mockups/eolarity-redesign/Unexpected.tsx": () => import("../components/mockups/eolarity-redesign/Unexpected.tsx")
};
